env:
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 5
globals:
  Promise: false
  Map: false
rules:
  strict:
    - error
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
